package editor.ui;

public enum GuiCommand
{
  SAVE_MAP,  NEW_FILE,  OPEN_FILE,  SAVE_AS,  SAVE_OBJECTS,  LOAD_OBJECTS,  EXPORT_OBJ,  IMPORT_MODELS,  IMPORT_COLLIDERS,  IMPORT_ZONES,  COMPILE_SHAPE,  COMPILE_COLLISION,  SELECT_OBJECTS,  SELECT_TRIANGLES,  SELECT_VERTICIES,  SHOW_TRANSLATE_SELECTION_DIALOG,  SHOW_ROTATE_SELECTION_DIALOG,  SHOW_SCALE_SELECTION_DIALOG,  SHOW_RESIZE_SELECTION_DIALOG,  SHOW_FLIP_SELECTION_DIALOG,  SHOW_CREATE_PRIMITIVE_MODEL_DIALOG,  SHOW_GENERATE_UV_DIALOG,  SHOW_GENERATE_COLLIDER_DIALOG,  SEPARATE_VERTS,  FUSE_VERTS,  JOIN_MODELS,  SPLIT_MODEL,  JOIN_COLLIDERS,  SPLIT_COLLIDER,  JOIN_ZONES,  SPLIT_ZONE,  SHOW_CREATE_PRIMITIVE_COLLIDER_DIALOG,  SHOW_CREATE_PRIMITIVE_ZONE_DIALOG,  SHOW_CREATE_MARKER_DIALOG,  SHOW_CHOOSE_COLOR_DIALOG,  CREATE_COLLIDER_GROUP,  CREATE_ZONE_GROUP,  CONVERT_COLLIDER_TO_ZONE,  CONVERT_ZONE_TO_COLLIDER,  SELECT_ALL_WITH_TEXTURE,  SHOW_TEXTURE_SCROLL,  SHOW_SHORTCUTS,  SHOW_EDITOR_PREFERENCES;
  
  private GuiCommand() {}
}
